MTES-MCT/qualicharge

Makefile, README.md, bin/pytest, src/api/Dockerfile, src/api/Pipfile, src/api/Pipfile.lock, src/api/pyproject.toml, src/api/qualicharge/__init__.py, src/api/qualicharge/api/__init__.py, src/api/qualicharge/api/v1/__init__.py, src/api/tests/__init__.py, src/api/tests/test_api.py
Integrate pytest and the black/ruff/mypy linters trio.
=> 🔧(api) add linters and tests runner

.github/workflows/docker-image.yml, .github/workflows/python-app.yml
Add first workflows for the API Python application and Docker image building.
=> 👷(project) add CI workflows

CHANGELOG.md, src/api/pyproject.toml
- Add a custom exception handler for authentication failures
=> 🔖(patch) bump release to 0.2.1

CHANGELOG.md, src/api/qualicharge/api/v1/routers/statique.py
We need to quickly draft API design so that we can share it with our partners.
=> ✨(api) add create and update endpoints for statique objects

CHANGELOG.md, src/api/pyproject.toml
- Implement static data database schemas
- Mark Static.id_pdc_itinerance field as required
=> 🔖(minor) bump release to 0.4.0

src/api/tests/schemas/test_static.py
We observed flaky tests, but are not able to reproduce them.
Test various phone number formats.
=> ✅(api) add tests for operateur phone numbers

renovate.json
Could be useful for PR triage.
=> 🔧(project) add "dependencies" label to renovate PRs

renovate.json
A weekly update of python dependencies will be easier to handle and will save kittens!
=> 🔧(project) switch to weekly renovate PRs

CHANGELOG.md, src/api/pyproject.toml
- Implement statique router endpoints
- Draft dynamique database schemas
- Implement dynamique router endpoints
- Switch to TimescaleDB
- Upgrade FastAPI to 0.111.0
=> 🔖(minor) bump release to 0.5.0

CHANGELOG.md, src/api/pyproject.toml
-   Implement `OperationalUnit` schema
-   Link `OperationalUnit` to `Station` using AFIREV prefixes
-   Implement `User` and `Group` schemas
-   Implement `User` scopes (fine-tuned permissions)
-   Implement row permissions on API endpoints (given assigned operational units)
-   Integrate OAuth2 password flow authentication fallback when OIDC is not enabled
=> 🔖(minor) bump release to 0.6.0

CHANGELOG.md, src/api/Pipfile, src/api/Pipfile.lock, src/api/qualicharge/api/v1/routers/auth.py, src/api/qualicharge/auth/oidc.py, src/api/qualicharge/factories/static.py, src/api/tests/api/v1/routers/test_auth.py, src/api/tests/auth/test_oidc.py
Python-jose has numerous critical security issues that don't seem to be handled by project's author. Let's move to a well maintained project to encode/decode JWT tokens.
Reference: https://github.com/advisories/GHSA-ffqj-6fqr-9h24
=> Switch to PyJWT

CHANGELOG.md, src/api/pyproject.toml, src/api/qualicharge/__init__.py
- Track user last login date time
- CLI: remove the scopes column from the `list-users` command
- CLI: the `username` parameter is now required for the `create-user` command
- CLI: add the `read-user` command
- CLI: fix `create-user` command failure when no group exists (#70)
=> 🔖(minor) bump release to 0.8.0

docs/README.md
Gitbook to Github sync is broken.
=> 🐛(docs) add gitbook's root README.md

CHANGELOG.md, src/api/pyproject.toml, src/api/qualicharge/__init__.py
- Document API authentication flow
- Document API data schemas
- Upgrade `pydantic-extra-types` to `2.8.0`
- Upgrade `pydantic-settings` to `2.3.1`
- Upgrade `sentry-sdk` to `2.5.1`
- Upgrade `sqlmodel` to `0.0.19`
- Improve database transactions in statique endpoints
- Allow to update all statique-related model fields
=> 🔖(minor) bump release to 0.9.0

.github/workflows/python-packages.yml, README.md, src/client/CHANGELOG.md, src/client/LICENSE, src/client/README.md
We want to publish the `qcc` client and CLI to PyPI.
=> Improve client python packaging

.github/workflows/python-packages.yml
Don't forget to install poetry!
=> 🐛(github) fix PyPI publication workflow

.github/workflows/python-packages.yml
=> 🐛(github) fix PyPI workflow artifact path

.github/workflows/python-packages.yml
=> 🐛(github) fix PyPI workflow dist path

.github/workflows/python-packages.yml, src/client/README.md
=> Fix docs and CI

env.d/opendata, src/opendata/CHANGELOG.md, src/opendata/Pipfile, src/opendata/Pipfile.lock, src/opendata/settings.yaml
Data7 0.6.0 release offers huge performance improvements, yay!
https://github.com/jmaupetit/data7/releases/tag/v0.6.0
=> ⬆️(opendata) upgrade data7 to 0.6.0

env.d/notebook, src/notebook/example.md
=> 🔨 (notebook) add example of Metabase API

src/api/Pipfile.lock
During previous dependencies upgrade, I forgot to update the `Pipfile.lock` file and broke the build.
=> 🐛(api) update Pipfile lock

src/notebook/indicators/reference_indicators.md, src/notebook/misc/create_indicators.md, src/notebook/misc/create_query.py
Update the first version of the indicators notebook `reference_indicators.md`:
=> 🔨 (notebook) Update indicators notebook

src/api/CHANGELOG.md, src/api/start.sh
Drastically improve performances in production by allowing to scale workers on a single node.
=> ⚡️(api) allow uvicorn workers configuration

scripts/_common.sh, scripts/create-api-users.sh, scripts/reset-password.sh
Because people forget...
This scripts reset user password and send the new password in a Vault Sent. Vault infornations are sent by email.
=> ⚡️(api) add user password reset script

.github/workflows/api.yml, .github/workflows/client.yml, .github/workflows/dashboard.yml, .github/workflows/docker-images.yml, .github/workflows/prefect.yml
We don't need to execute the whole CI if we only changed things in the client. Let's save some kitties! 😸
=> 👷(project) filter CI workflows given changed paths

src/dashboard/apps/consent/admin.py, src/dashboard/apps/core/admin.py
Improved admin panels to simplify consent management for admins.
Added search_fields, list_display, and list_filter  for Consent, Entity and DeliveryPoint.
=> 🚸(dashboard) enhance admin panels

env.d/dashboard, src/dashboard/CHANGELOG.md, src/dashboard/Pipfile, src/dashboard/Pipfile.lock, src/dashboard/dashboard/settings.py
Sentry integration to enable error tracking and performance monitoring
- install Sentry SDK and DjangoIntegration to Sentry.
- add Sentry configuration in `settings.py`.
- add `SENTRY_DSN` to .env
=> 🔊(dashboard) add Sentry integration

src/dashboard/Pipfile.lock
Pipfile.lock was out of date
lock pipenv
=> ⬆️(dashboard) update dependencies in Pipfile.lock

src/api/qualicharge/migrations/versions/3e8ea07e5b66_alter_db_enum_to_varchar.py
Previous downgrade implementation was broken.
=> 🐛(api) fix database enums to varchar migration (1.5)

src/opendata/CHANGELOG.md, src/opendata/data7.yaml
Now that we've implemented a materialized view for static data, let's use it! This will speed-up API responses!
=> ⚡️(opendata) use the Statique Materialized View

src/notebook/misc/analyze-scalingo-logs.md
We need more insights on API performance.
In the meantime, waiting for a deployed log platform, we performed a draft analysis.
=> 🧐(notebook) explore API response time

README.md
We no longer are in the build phase.
Remove warnings and add docs.
=> 📝(project) update project's README

scripts/_common.sh
Now that we will create accounts on different instances, we need to be able to choose which instance we are targeting.
=> ✨(scripts) handle multiple API instances

src/notebook/CHANGELOG.md, src/notebook/misc/migrate_metabase_questions.md
Metabase Dashboards and Questions are present in staging platform.
We have to migrate they to the new production platform.
Create a python script to migrate Questions. 
This script use Metabase API.
=> ✨(notebook) migrate Metabase questions

src/dashboard/CHANGELOG.md, src/dashboard/apps/auth/admin.py, src/dashboard/apps/auth/mails.py, src/dashboard/apps/auth/models.py, src/dashboard/apps/auth/tests/test_mails.py, src/dashboard/apps/auth/tests/test_models.py
Administrators must be able to validate many users in the admin.
=> ✨(dashboard) add user validation action and email notifications

.github/workflows/prefect.yml, env.d/prefect-qc, src/prefect/CHANGELOG.md, src/prefect/Dockerfile, src/prefect/Pipfile, src/prefect/Pipfile.lock, src/prefect/indicators/infrastructure/i1.py, src/prefect/prefect.yaml, src/prefect/pyproject.toml, src/prefect/quality/expectations/static.py, src/prefect/quality/flows/static.py, src/prefect/quality/templates/static-by-amenageur.md.j2, src/prefect/tests/quality/__init__.py, src/prefect/tests/quality/test_static.py
For now, we manually test data consistency and make a quality report to operators sending data. This can be automated using appropriate tools.
=> Integrate Great Expectations

src/api/CHANGELOG.md, src/api/qualicharge/api/v1/__init__.py, src/api/qualicharge/api/v1/routers/manage.py, src/api/qualicharge/auth/schemas.py, src/api/tests/api/v1/routers/test_manage.py, src/client/CHANGELOG.md, src/client/qcc/cli/__init__.py, src/client/qcc/cli/manage.py, src/client/qcc/client.py, src/client/qcc/endpoints/dynamic.py, src/client/qcc/endpoints/manage.py, src/client/tests/cli/test_manage.py, src/client/tests/endpoints/test_manage.py
We need API endpoints for QualiCharge services interconnexion.
=> [API] add management endpoints

src/prefect/clean-offline-workers.sh, src/prefect/cron.json, src/prefect/post-deploy.sh, src/prefect/prefect-deploy-all.sh, src/prefect/prefect.yaml, src/prefect/start.sh
New Prefect deployment cannot be created while the previous release of the API server is running. It cannot be done even in a post-deployment step.
=> Improve prefect deployment

src/dashboard/apps/core/helpers.py, src/dashboard/apps/core/management/commands/syncdeliverypoints.py, src/dashboard/apps/core/tests/test_helpers.py
New awaiting consents are checked every 7 days.
However, if a new consent is created following synchronization with the QualiCharge API, we don't want the user to wait that long for a notification.
Therefore, a notification must be sent immediately after the new consents are created.
=> ✨(dashboard) enhance `syncdeliverypoints` command to send email

src/api/CHANGELOG.md, src/api/qualicharge/fixtures/operational_units.py, src/api/qualicharge/migrations/versions/ff52adf974c7_operational_units_data_update.py
A CPO is willing to submit data for a new operational unit.
Given latest assigned codes, we've updated 1 existing operational unit and created 12 new ones.
=> 🗃️(api) update operational units

src/dashboard/CHANGELOG.md, src/dashboard/apps/renewable/__init__.py, src/dashboard/apps/renewable/admin.py, src/dashboard/apps/renewable/apps.py, src/dashboard/apps/renewable/migrations/__init__.py, src/dashboard/apps/renewable/models.py, src/dashboard/apps/renewable/views.py, src/dashboard/dashboard/settings.py
Introduced a new Django app, `renewable`, to the Django project.
=> ✨(dashboard) add renewable_meter app to the dashboard project

src/notebook/misc/api-benchmark.md
Now that we assess API performance using locust, we need to analyze collected data.
=> Add API performance analysis

src/prefect/CHANGELOG.md, src/prefect/indicators/infrastructure/i4.py, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/prefect.yaml, src/prefect/tests/infrastructure/test_i4.py
=> 🔖(prefect) add indicators i4

src/prefect/CHANGELOG.md, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/indicators/usage/u5.py, src/prefect/prefect.yaml, src/prefect/tests/usage/test_u5.py
=> 🔖(prefect) add indicators u5

src/prefect/CHANGELOG.md, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/indicators/usage/u6.py, src/prefect/prefect.yaml, src/prefect/tests/usage/test_u6.py
=> 🔖(prefect) add indicators u6

src/prefect/CHANGELOG.md, src/prefect/indicators/infrastructure/i7.py, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/prefect.yaml, src/prefect/tests/infrastructure/test_i7.py
Complete the existing indicators.
=> 🔖(prefect) add i7 indicator

src/prefect/CHANGELOG.md, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/indicators/usage/u9.py, src/prefect/prefect.yaml, src/prefect/tests/usage/test_u9.py
=> 🔖(prefect) add indicators u9

src/prefect/CHANGELOG.md, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/indicators/usage/u10.py, src/prefect/prefect.yaml, src/prefect/tests/usage/test_u10.py
=> 🔖(prefect) add indicators u10

.github/workflows/chore.yml, .github/workflows/dashboard.yml, .github/workflows/docker-images.yml, .github/workflows/python-packages.yml
GitHub actions recommends defining a default permission for each workflow.
Set default permissions to:
```yaml
permissions:
contents: read
```
=> 👷(project) fix base workflow permissions

src/api/CHANGELOG.md, src/api/pyproject.toml, src/api/qualicharge/__init__.py
- Introduce two new database connection settings:
- `DB_CONNECTION_POOL_CHECK`
- `DB_CONNECTION_POOL_RECYCLE`
- Upgrade `pyarrow` to `20.0.0`
- Upgrade `pydantic` to `2.11.3`
- Upgrade `pydantic-extra-types` to `2.10.4`
- Upgrade `pydantic-settings` to `2.9.1`
- Upgrade `sentry-sdk` to `2.27.0`
- Upgrade `setuptools` to `80.0.0`
=> 🔖(api:minor) bump release to 0.23.0

src/prefect/CHANGELOG.md, src/prefect/indicators/run.py, src/prefect/indicators/strategy.py, src/prefect/indicators/usage/u12.py, src/prefect/prefect.yaml, src/prefect/tests/usage/test_u12.py
Complete the existing indicators.
=> 🔖(prefect) add u12 indicator

scripts/create-api-users.sh
Users may want to read sent point of charge statuses.
=> 🔧(api) add 'dynamic:read' to new users default scope

src/dashboard/CHANGELOG.md, src/dashboard/dashboard/__init__.py
- bootstrap dashboard project
- add a base view combining mixins for consistency
- add dashboard homepage
- integrate custom 403, 404, and 500 error pages
- add API connector for the "Annuaire des Entreprises" API
- add API connector for the QualiCharge API
- add Sentry integration
- add custom user model
- add ProConnect authentication system
- add `UserValidationMixin` to ensure access restrictions for unvalidated users
- add a specific restricted view for unvalidated users
- add mass admin action to validate users
- add core app with `Entity` and `DeliveryPoint` models
- add admin integration for `Entity`, `DeliveryPoint` and `Station`
- add a helper function to sync delivery points and stations from the QualiCharge API
- add a helper function to retrieve company information from its …
=> 🔖(dashboard:minor) bump release to 0.1.0

src/dashboard/apps/core/factories.py, src/dashboard/apps/renewable/forms.py, src/dashboard/apps/renewable/templates/renewable/forms/widgets/checkbox.html, src/dashboard/apps/renewable/templates/renewable/includes/_manage_meters.html, src/dashboard/apps/renewable/templates/renewable/includes/_manage_meters_authorisations.html, src/dashboard/apps/renewable/templates/renewable/manage.html, src/dashboard/apps/renewable/tests/test_forms.py, src/dashboard/apps/renewable/tests/test_view.py, src/dashboard/apps/renewable/urls.py, src/dashboard/apps/renewable/views.py
Implementation of a form allowing users to submit their renewable energy meter readings with data validation.
=> ✨(renewable) add renewable meter reading management and validations

src/api/tests/api/v1/routers/test_statique.py
We needed to ensure that the `updated_at` field is updated even when we submit unchanged static data using the (bulk) update endpoints.
=> ✅(api) add integration tests for static-related updated_at fields

src/dashboard/readme.md
Update the documentation for the renewable app
=> 📝(dashboard) update documentation

src/dashboard/CHANGELOG.md
Add new renewable features in the CHANGELOG.md
=> 📝(dashboard) update changelog

.github/workflows/prefect.yml, src/prefect/cooling/sessions.py, src/prefect/prefect.yaml, src/prefect/tests/cooling/test_sessions.py
Now that we are operational with sessions cooling, let's apply the same pattern to sessions.
=> Prefect sessions cooling

src/api/CHANGELOG.md, src/api/cron.json, src/api/scripts/clean-old-activity.sql
We need to periodically clean the activity table as it's growing exponentially.
=> 🗃️(api) add activity data cleaning cronjob

docker-compose.yml, src/prefect/Dockerfile, src/prefect/Procfile.dev, src/prefect/cooling/__init__.py, src/prefect/pyproject.toml, src/prefect/tests/cooling/test_sessions.py, src/prefect/tests/cooling/test_statuses.py
When a daily archive already exists, one should be able to check if it contains all expected records from the database and fail if not.
=> [Prefect:cooling] add if exists "check" strategy

src/dashboard/CHANGELOG.md, src/dashboard/apps/__init__.py, src/dashboard/dashboard/__init__.py, src/dashboard/pyproject.toml
Updated `__version__` to 0.2.0 and added corresponding changes to the changelog with a new release reference.
- Upgrade `Django` to `5.2.2`
- Upgrade `jsonschema` to `4.24.0`
- Upgrade `requests` to `2.32.4`
- Upgrade `urllib3` to `2.5.0`
- Upgrade `pydantic` to `2.10.0` 
- Upgrade `pygments` to `2.19.2`
- add `renewable` app
- add `Renewable` model with admin interface
- add `get_current_quarter_date_range` utility
- add `renewable` dashboard card
- add a formset and view for managing renewable delivery point statuses
- add meter reading management interface with form validation
- add a view for submitted renewable meter readings
- add entity handling with EntityMixin
- add utility functions for quarter-based date operations to handle quarter-specific
date calculations and conversions
- …
=> 🔖(dashboard) bump release to 0.2.0

.gitignore, Makefile, docker-compose.yml, src/notebook/tiruert/integration-carbure.md
We need to test our integration with CARBURE to automate TIRUERT reports.
=> Experiment with CARBURE API to sent TIRUERT reports

.github/workflows/api.yml, Makefile, bin/qcm, scripts/_common.sh, scripts/create-api-users.sh, scripts/reset-password.sh, src/api/CHANGELOG.md, src/api/cron.json, src/api/pyproject.toml, src/api/qualicharge/cli.py, src/api/tests/test_cli.py
We now often use the management CLI, let's ease our life by making it a bit more user-friendly.
=> [API] Improve QualiCharge management CLI

src/api/qualicharge/api/v1/routers/static.py, src/api/tests/api/v1/routers/test_statique.py
We are in transition where stored statique data may be invalid when requested as the Statique model evolved.
Instead of raising a confusing 500 error in this case, raise a 422 error with an explicit message.
=> 🚸(api) raise an explicit 422 error when statique data is invalid

.github/workflows/prefect.yml, src/prefect/CHANGELOG.md, src/prefect/prefect.yaml, src/prefect/quality/expectations/dynamic.py, src/prefect/quality/expectations/parameters.py, src/prefect/quality/expectations/static.py, src/prefect/tests/quality/test_dynamic.py, src/prefect/tests/quality/test_static.py
Add quality Expectations for sessions
=> 🔖(prefect) Add quality Expectations for sessions
