MTES-MCT/qualicharge

.github/workflows/chore.yml
.github/workflows/docker-image.yml
.github/workflows/python-app.yml
CHANGELOG.md

We need a changelog to follow project changes between releases.

Add changelog

---

src/api/Pipfile
src/api/Pipfile.lock

httpx is required in production!
We did not notice as `pytest-httpx` installs `httpx` in a development environment.

➕(api) add missing httpx dependency for production

---

CHANGELOG.md
src/api/qualicharge/api/v1/__init__.py
src/api/qualicharge/auth/oidc.py
src/api/qualicharge/exceptions.py
src/api/tests/api/v1/test_root.py
src/api/tests/test_auth.py

When an ID token expires or is invalid, we should respond with a 403 status and an appropriate error message instead of a 500.

🐛(api) return a 403 HTTP status upon authentication failure

---

.gitignore
CHANGELOG.md
Makefile
bin/pipenv
docker-compose.yml
src/api/Pipfile
src/api/Pipfile.lock
src/api/qualicharge/api/v1/__init__.py
src/api/qualicharge/api/v1/routers/__init__.py
src/api/qualicharge/api/v1/routers/auth.py
src/api/qualicharge/api/v1/routers/statique.py
src/api/qualicharge/conf.py
src/api/qualicharge/factories/__init__.py
src/api/qualicharge/factories/static.py
src/api/qualicharge/models/__init__.py
src/api/qualicharge/models/static.py
src/api/tests/api/v1/routers/__init__.py
src/api/tests/api/v1/routers/test_auth.py
src/api/tests/api/v1/routers/test_statique.py
src/api/tests/models/__init__.py
src/api/tests/models/test_static.py

We need to support the official IRVE statique data schema [1] to create and fetch statique entries.
1. https://schema.data.gouv.fr/etalab/schema-irve-statique/2.3.1/documentation.html

Add IRVE static schema and API endpoints

---

src/api/qualicharge/api/v1/routers/statique.py
src/api/tests/api/v1/routers/test_statique.py

Using factories even for demonstration purpose was a bad idea since Polyfactory is not installed in non-development environment.
For now the `/statique` list entrypoint returns an empty list.

🐛(api) remove factory usage in /statique list endpoint

---

CHANGELOG.md
src/api/qualicharge/api/v1/__init__.py
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/api/v1/routers/static.py
src/api/qualicharge/factories/dynamic.py
src/api/qualicharge/models/dynamic.py
src/api/tests/models/test_dynamic.py

We will collect near-real time point of charge statuses and sessions.
-   [x] add `Status` dynamic model
-   [x] add `/dynamique/status/` endpoints
-   [x] add `Session` dynamic model
-   [x] add `/dynamique/session/` endpoints
Status schema is available at:
https://schema.data.gouv.fr/etalab/schema-irve-dynamique/2.3.1/documentation.html

✨(api) add dynamic Status and Session models + API endpoints

---

CHANGELOG.md
src/api/pyproject.toml

- Define `/dynamique` endpoints
- Define dynamic status and session models
- Define `/statique` endpoints and models
- Move the `/whoami` endpoint to the `/auth` router

🔖(minor) bump release to 0.3.0

---

src/api/qualicharge/api/v1/routers/dynamic.py
src/api/tests/api/v1/routers/test_dynamic.py

We need to filter:
- status list by:
* station
* pdc
* lower limit horodatage date
- PDC status history by:
* lower limit horodatage date
⚠️ Note that filters are cumulative.

✨(api) add dynamic enpoint filters

---

.github/workflows/python-app.yml
src/api/qualicharge/migrations/versions/fda96abb970d_add_operational_unit_data.py

Recent changes in the `get_session` database utility broke a database migration.

Fix database migration

---

CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/api/v1/routers/static.py
src/api/qualicharge/auth/schemas.py
src/api/qualicharge/factories/dynamic.py
src/api/qualicharge/factories/static.py
src/api/qualicharge/models/static.py
src/api/qualicharge/schemas/utils.py
src/api/tests/api/v1/routers/test_dynamic.py
src/api/tests/api/v1/routers/test_statique.py
src/api/tests/auth/test_schemas.py
src/api/tests/models/test_static.py
src/api/tests/schemas/test_utils.py

We need to ensure that request user only have access to data link to its organization, _e.g._ its groups and related operational units.

Add row permissions

---

src/api/qualicharge/api/v1/__init__.py
src/api/qualicharge/auth/oidc.py
src/api/qualicharge/exceptions.py

We now use the more generic AuthenticationError that works for both OIDC and OAuth2 password flows.

⚰️(api) remove unused OIDCAuthenticationError

---

src/api/qualicharge/__init__.py
src/api/qualicharge/api/__init__.py

Depending on the way QualiCharge is installed, the package version may not be available using importlib.metadata module. Leading to deployment failure during application's boot.
Let's use a less elegant but explicit way to declare/fetch project's version using a root `__version__` variable.

🐛(project) fix version fetching in Sentry integration

---

CHANGELOG.md
Makefile
bin/qualicharge
src/api/Pipfile
src/api/Pipfile.lock
src/api/qualicharge/__main__.py
src/api/qualicharge/auth/schemas.py
src/api/qualicharge/cli.py
src/api/tests/conftest.py
src/api/tests/fixtures/cli.py
src/api/tests/test_cli.py

We need a CLI for admin tasks, such as users and groups managements.

Add qualicharge command line interface

---

CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Integrate Sentry
- Manage users and groups using a new CLI
- Switch from `python-jose` to `PyJWT` as the [CVE-2022-29217](https://github.com/advisories/GHSA-ffqj-6fqr-9h24) does not seem to be fixed

🔖(minor) bump release to 0.7.0

---

CHANGELOG.md
src/api/qualicharge/cli.py
src/api/tests/test_cli.py

After testing it in staging environment, the CLI needs few minor improvements.

Improve CLI

---

.gitbook.yaml

We want our documentation to live in `./docs`.

🔧(docs) configure gitbook

---

renovate.json

We do not want a PR per updated dependency.
Configure renovate to also support poetry packages.

🔧(project) add poetry support to renovate configuration

---

bin/qcc
src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/tests/api/v1/routers/test_dynamic.py
src/client/qcc/cli/__init__.py
src/client/qcc/cli/api.py
src/client/qcc/cli/session.py
src/client/qcc/cli/static.py
src/client/qcc/cli/status.py
src/client/qcc/cli/utils.py
src/client/qcc/client.py
src/client/qcc/endpoints/base.py
src/client/qcc/endpoints/dynamic.py
src/client/qcc/endpoints/static.py
src/client/tests/cli/test_session.py
src/client/tests/cli/test_status.py
src/client/tests/endpoints/test_dynamic.py
src/client/tests/endpoints/test_static.py
src/client/tests/test_client.py

The API client and CLI needs to support dymanic endpoints.

[client] add dynamic endpoints support

---

.github/workflows/python-packages.yml

Instead of failing during PyPI package publication, we now only build/publish the client python package when releasing the client and only the client.

👷(github) release client only when tagging client release

---

docs/README.md
docs/schemas.md
docs/user/auth.md

French flag using the :fr: emoji code are not supported by gitbook, replaced them using the unicode character.
Also don't forget to specify the language for a code block.

📝(api) fix minor typos

---

.gitignore
Makefile
bin/jupytext
docker-compose.yml
src/api/Dockerfile
src/notebook/Dockerfile

We need a way to analyse your data and design our indicators locally.

Add notebook service

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- API dynamique bulk requests now returns the number of created items
- Upgrade alembic to `1.13.2`
- Upgrade Pydantic to `2.7.4`
- Upgrade pydantic-settings to `2.3.4`
- Upgrade pydantic-extra-types to `2.8.2`
- Upgrade email-validator to `2.2.0`
- Upgrade sentry-sdk to `2.7.1`

🔖(minor) bump release to 0.10.0

---

Makefile
bin/data7
bin/pipenv
docker-compose.yml
env.d/opendata
src/opendata/.secrets.yaml
src/opendata/CHANGELOG.md
src/opendata/Dockerfile
src/opendata/Pipfile
src/opendata/Pipfile.lock
src/opendata/Procfile
src/opendata/data7.yaml
src/opendata/settings.yaml

We need to publish dynamic datasets for:
-   "statique" data (charge points)
-   "dynamique" data (charge point statuses)
-   [x] integrate [Data7](https://github.com/jmaupetit/data7) to generate our datasets
-   [x] configure Scalingo deployment

Add Data7-based opendata service

---

src/api/CHANGELOG.md
src/api/qualicharge/db.py

The singleton pattern is not thread-safe leading to database session inconsistency during server heavy load (expired sessions, etc.)
See raised errors in SQLAlchemy docuementation: https://docs.sqlalchemy.org/en/20/errors.html#error-bhk3
Get a new session everytime it needs to be injected. Hope this won't create too many database connections.

🐛(api) fix not thread-safe database session singleton

---

.gitignore
docker-compose.yml
env.d/notebook
src/notebook/Dockerfile
src/notebook/example.md

We will fetch and write data from a PostgreSQL database to calculate various indicators and perform data analysis. Having example snippets as getting started examples would be a plus.

🔨(notebook) add example notebook that interacts with the database

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Allow to configure `API_STATIQUE_PAGE_MAX_SIZE` and `API_STATIQUE_PAGE_SIZE` independently from `API_STATIQUE_BULK_CREATE_MAX_SIZE`
- Store french administrative levels and geographic boundaries (shapes)
- Upgrade fastapi to `0.112.0`
- Upgrade geoalchemy2 to `0.15.2`
- Upgrade pydantic-settings to `2.4.0`
- Upgrade PyJWT to `2.9.0`
- Upgrade sentry-sdk to `2.13.0`
- Upgrade SQLModel to `0.0.21`
- Switched to Psycopg 3.x
- Add relevant data examples for Swagger
- Improve database session management
- `PointDeCharge.id_pdc_itinerance` should be unique

🔖(api:minor) bump release to 0.11.0

---

src/api/CHANGELOG.md
src/api/qualicharge/api/__init__.py
src/api/qualicharge/api/utils.py
src/api/qualicharge/api/v1/__init__.py
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/api/v1/routers/static.py
src/api/qualicharge/conf.py
src/api/tests/api/v1/routers/test_dynamic.py
src/api/tests/api/v1/routers/test_statique.py
src/client/CHANGELOG.md
src/client/qcc/conf.py
src/client/qcc/endpoints/base.py
src/client/tests/endpoints/test_dynamic.py
src/client/tests/endpoints/test_static.py

We need to limit bandwidth usage when dealing with heavy payload, particularly for `/bulk` endpoints now accepting a huge number of items.

Add gzip compression support in bulk endpoints

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/api/v1/routers/static.py
src/api/tests/api/v1/routers/test_dynamic.py
src/api/tests/api/v1/routers/test_statique.py

When paginating over object lists to submit, if the last page only contains a single item, the API will respond with a 422 HTTP status as we currently expect at least 2 items in the payload. This is obviously a edge case that needs to be handled.

Allow to submit single item in bulk endpoints

---

src/client/CHANGELOG.md
src/client/pyproject.toml

- Compress requests for bulk endpoints
- Upgrade Pydantic to `2.7.4`
- Upgrade pydantic-settings to `2.4.0`
- Upgrade typer to `0.12.5`
- Upgrade httpx to `0.27.2`

🔖(client:minor) bump release to 0.2.0

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Implement GZip requests support (mostly for bulk endpoints)
- Implement Pandas-based `StatiqueImporter`
- CLI: add `import-statique` command
- Require the `code_insee_commune` field in both the `Statique` model and the `Localisation` schema
- Allow to submit a single item in bulk endpoints
- Add create or update support for the `/statique/bulk` endpoints (with improved performances)
- Upgrade fastapi to `0.112.2`
- Upgrade typer to `0.12.5`
- Upgrade sqlmodel to `0.0.22`

🔖(api:minor) bump release to 0.12.0

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Migrate administrative boundaries tables schema and data
- Add geo-boundaries population and area fields
- Upgrade alembic to `1.13.3`
- Upgrade fastapi to `0.115.0`
- Upgrade pandas to `2.2.3`
- Upgrade Psycopg to `3.2.3`
- Upgrade Pydantic to `2.9.1`
- Upgrade pydantic-settings to `2.5.2`
- Upgrade pyinstrument to `4.7.3`
- Upgrade python-multipart to `0.0.12`
- Upgrade sentry-sdk to `74.1.2`

🔖(api:minor) bump release to 0.13.0

---

src/api/CHANGELOG.md
src/api/qualicharge/migrations/versions/6e610f62bcc6_add_missing_fk.py

Some constraints linked to recent database schema changes were missing: no primary keys and foreign keys was defined.

🗃️(api) add geo schemas missing constraints

---

src/api/CHANGELOG.md
src/api/qualicharge/conf.py
src/api/qualicharge/db.py

Default connection pool configuration values are particularily low for a production instance. One may want to adapt those given environment constraints and expected requests per seconds.

🗃️(api) allow database connections pool configuration

---

src/api/CHANGELOG.md
src/api/qualicharge/cli.py
src/api/tests/test_cli.py

It's usefull to serialize command output in JSON so that we can pipe the result in a `jq` black magic.

✨(api) add `--json` option to the `read-user` CLI command

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Allow uvicorn workers configuration in start script using the `QUALICHARGE_UVICORN_WORKERS` environment variable
- Make database engine connections pool size configurable (`DB_CONNECTION_POOL_SIZE` and `DB_CONNECTION_MAX_OVERFLOW` settings)
- Add a `--json` flag to the `read-user` CLI command
- Upgrade alembic to `1.14.0`
- Upgrade fastapi to `0.115.4`
- Upgrade pyarrow to `18.0.0`
- Upgrade pydantic-extras-types to `2.10.0`
- Upgrade pydantic-settings to `2.6.1`
- Upgrade pyinstrument to `5.0.0`
- Upgrade python-multipart to `0.0.17`
- Upgrade sentry-sdk to `2.18.0`
- Set fk to `NULL` when related table entry is deleted for the `Station` table
- Add missing City / Department table foreign key constraints

🔖(api:minor) bump release to 0.14.0

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/static.py
src/api/tests/api/v1/routers/test_statique.py

We don't want to provide debug information for all our users as it should only be used in development.

🔇(api) send DB query details on error only in debug mode

---

src/api/CHANGELOG.md
src/api/qualicharge/models/static.py
src/api/qualicharge/schemas/core.py
src/api/tests/models/test_static.py

The num_pdl field is required to be a 14-characters string for Enedis (French provider) and forbids defining a num_pdl for other providers.  Let's move to a more generic 64-chars string.

🗃️(api) make `num_pdl` field less provider-specific

---

src/api/Pipfile.lock

An out-dated Pipenv lock file breaks the build and underlying deployment.

🐛(api) update Pipenv lock file

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Upgrade fastapi to `0.115.5`
- Upgrade geoalchemy2 to `0.16.0`
- Upgrade pyjwt to `2.10.0`
- Upgrade setuptools to `75.5.0`
- Send DB query details on Statique API errors only in debug mode
- Move `num_pdl` field to a 64-chars string
- Return created objects UUIDs for statuses and sessions

🔖(api:minor) bump release to 0.15.0

---

src/dashboard/Pipfile
src/dashboard/Pipfile.lock
src/dashboard/apps/auth/factories.py
src/dashboard/apps/auth/tests/test_models.py
src/dashboard/apps/consent/factories.py
src/dashboard/apps/consent/tests/test_models.py
src/dashboard/apps/core/factories.py
src/dashboard/apps/core/tests/test_models.py

Use Factory Boy to generate factories and integrate them into existing tests
- Add factory-boy to Pipfile
- add factories for the models : auth.DashboardUser, consent.Consent, core.Entity, core.DeliveryPoint
- Update tests with new factories

✅(dashboard) update tests with factory boy

---

Makefile
src/dashboard/apps/consent/fixtures/__init__.py
src/dashboard/apps/consent/fixtures/consent.py
src/dashboard/apps/consent/management/__init__.py
src/dashboard/apps/consent/management/commands/__init__.py
src/dashboard/apps/consent/management/commands/seed_consent.py

Add fixtures to streamline the development of consent management features

🌱(dashboard) add consent development fixtures

---

.github/workflows/api.yml

The `bench-api` CI job fails when a PR has been merged to main, since it tries to publish a comment in a non existing PR.

👷(api) post performance md table only in PR

---

.github/workflows/api.yml

When a PR is merged, we don't want to post a comment in the PR conversation as there is no conversation. Hence, we should skip irrelevant steps in the `bench-api` job.

Fix bench jobs when a PR is merged

---

src/api/CHANGELOG.md
src/api/qualicharge/models/static.py
src/api/qualicharge/schemas/core.py
src/api/tests/models/test_static.py
src/api/tests/schemas/test_static.py

Today is not a past date but is a perfectly acceptable value for the `date_maj` field.

🐛(api) allow `date_maj` field to be set to "today"

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/static.py
src/api/tests/api/v1/routers/test_statique.py

If a user submits the same payload twice using the `/statique/` (POST) endpoint, the API returns a 201 CREATED. And if the payload is slightly modified (with the same `id_pdc_itinerance`), we cannot guaranty what would be created or updated. This use-case should be forbidden.

Forbid /statique/ POST usage for an existing PDC

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Upgrade fastapi to `0.115.6`
- Upgrade httpx to `0.28.1`
- Upgrade pyarrow to `18.1.0`
- Upgrade pydantic to `2.10.3`
- Upgrade pydantic-extra-types `2.10.1`
- Upgrade python-multipart to `0.0.19`
- Upgrade sentry-sdk to `2.19.2`
- Upgrade typer to `0.15.1`
- Allow `date_maj` field to be set to "today"
- Forbid `/static/` POST usage for an existing PDC

🔖(api:minor) bump release to 0.16.0

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/api/v1/routers/static.py
src/api/qualicharge/auth/oidc.py
src/api/qualicharge/db.py
src/api/qualicharge/schemas/utils.py
src/api/tests/auth/test_oidc.py
src/api/tests/schemas/test_utils.py

The request user is injected in every API endpoint. Not prefetching related objects such as groups and operational units generates a huge number of unexpected queries and slows down API response time.

API: improve database queries

---

src/dashboard/apps/consent/fixtures/consent.py
src/dashboard/apps/consent/forms.py
src/dashboard/apps/consent/mixins.py
src/dashboard/apps/consent/templates/consent/forms/widgets/checkbox.html
src/dashboard/apps/consent/templates/consent/manage.html
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/urls.py
src/dashboard/apps/consent/views.py
src/dashboard/apps/core/factories.py

## Purpose
Validation of consents must be done via a global checkbox at the end of the form
Add a `BreadcrumbContextMixin` to streamline breadcrumb handling.

✨(dashboard) add the global consent

---

src/dashboard/Pipfile
src/dashboard/Pipfile.lock

"django-stubs" must be in the main dependency group in the Pipfile.
Moved "django-stubs" from dev-packages to the main dependency group in the Pipfile, as it's required broadly. 
Updated Pipfile.lock to reflect this change, ensuring compatibility with existing configurations.

⬆️(dashboard) add django-stubs to main dependencies in Pipfile

---

src/dashboard/apps/consent/models.py
src/dashboard/apps/consent/tests/test_admin.py

`Django admin` is sensitive to the order of `model manager` declarations. 
In order to display all data in the admin, it is important to use django's default model manager.

🐛(dashboard) adjust manager order in Consent model

---

Makefile
src/dashboard/readme.md

The `bootstrap` command in the `makefile` is too general and long to execute for working on the `dashboard` project alone. A specific `bootstrap` command for the `dashboard` project would be welcome.

🧑‍💻(dashboard) add bootstrap and reset commands for dashboard setup

---

src/api/CHANGELOG.md
src/api/qualicharge/auth/oidc.py

We need to track how users are using the API and who's raising observed errors.

🔧(api) set request user in Sentry's context

---

src/opendata/CHANGELOG.md
src/opendata/Pipfile
src/opendata/Pipfile.lock
src/opendata/Procfile
src/opendata/data7.yaml
src/opendata/settings.yaml

Now that we have production-ready data, we need to carefully configure data7 given its usage.

Update Data7 configuration

---

src/dashboard/Pipfile
src/dashboard/Pipfile.lock

Upgraded django-dsfr dependency from 1.4.5 to 2.0.0 in both Pipfile and Pipfile.lock.

⬆️(dashboard) update django-dsfr to version 2.0.0

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/static.py
src/api/qualicharge/models/static.py
src/api/qualicharge/schemas/utils.py
src/api/tests/api/v1/routers/test_statique.py
src/api/tests/models/test_static.py

The importation process may create many duplicates as the upsert technique we use does not compare rows with missing fields. Two tables are mostly concerned: Operateur and Amenageur. Hence we decided to fill optional (non filled) fields with default generic strings (e.g. "NA").

Set Statiques optional values to a default

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/admin.py
src/dashboard/apps/consent/tests/conftest.py
src/dashboard/apps/consent/tests/test_admin.py

Simplify updating consent status (awaiting and revoked) directly from the admin interface.

✨(dashboard) add admin actions for updating consent statuses

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/models.py
src/dashboard/apps/consent/tests/test_models.py

For contractual reasons, the validated consents cannot be modified.
It is therefore necessary to block the updates of all new data and the deletion of consents if a consent has the status "VALIDATED". 
Introduced a validation mechanism to block any changes to consents with a `VALIDATED` status, raising a `ValidationError` if attempted.

👔(dashboard) enforce immutability of validated consents

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/templates/consent/manage.html
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/views.py
src/dashboard/templates/blocks/main_menu.html

Consents with a status other than “AWAITING” cannot be changed by users.
The consent form uses the update() method and therefore cannot take advantage of the clean() method of the model.
The update() present in the view must be modified accordingly.
The user must be able to simply understand that he cannot update delivery points with a status "VALIDATED".
Fix the home URL in the navigation menu.

👔(dashboard) disabled updates to non-AWAITING consents in front app

---

src/api/CHANGELOG.md
src/api/qualicharge/migrations/versions/d3d2c20f8efd_update_enum_definitions.py

~~Mypy requires a more explict definition for Enum type fields.~~
The `raccordementemum` database type has never been fixed.

🐛(api) fix raccordementenum database type

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/admin.py
src/dashboard/apps/consent/tests/test_admin.py

According to the business rules, consents with status `VALIDATED` and `REVOKED`cannot be changed.
Therefore, the action `make awaiting`  has no interest and must be deleted.

🗑️(dashboard) remove "make awaiting" action from ConsentAdmin.

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/exceptions.py
src/dashboard/apps/consent/models.py
src/dashboard/apps/consent/tests/test_models.py
src/dashboard/readme.md

Validated consent can be changed to revoked. 
Only the `status` and `revoked_at` fields can be modified during this modification.

👔(dashboard) update consent status logic when update from validated to revoked

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/admin.py
src/dashboard/apps/consent/tests/test_admin.py

In admin, the deletion of `validated` and `revoked` consents must not be allowed.

👔(dashboard) disallow delete action for consents in admin.

---

Makefile
src/api/CHANGELOG.md
src/api/qualicharge/migrations/versions/3e8ea07e5b66_alter_db_enum_to_varchar.py
src/api/qualicharge/schemas/core.py
src/api/qualicharge/schemas/sql.py

By default, python-derived enum fields are stored using the enum name instead of its value in database. This forces us to map the corresponding value when exporting data.

API: migrate database enum from name to value (1)

---

src/api/qualicharge/migrations/versions/9ae109e209c9_update_db_enum_values_and_type.py

By default, python-derived enum fields are stored using the enum name instead of its value in database. This forces us to map the corresponding value when exporting data.
Now that we moved legacy enum (with keys) to a varchar column, we update enum keys to their corresponding values and switch back columns to the new enum (with values).
This is the second step of the database migration (for the first step, see #351).
We also had to fix previous migration in #354

API: migrate database enum from name to value (2)

---

Makefile
src/api/CHANGELOG.md
src/api/Pipfile
src/api/Pipfile.lock
src/api/cron.json
src/api/pyproject.toml
src/api/qualicharge/cli.py
src/api/qualicharge/migrations/env.py
src/api/qualicharge/migrations/versions/4b99d15436b0_add_statique_materialized_view.py
src/api/qualicharge/schemas/core.py
src/api/tests/schemas/test_static.py

Having a SQL materialized view for "statique" data would ease recurrent database queries joining the same tables frequently. Moreover this should speed up database queries and response time for API endpoints using them.

Add statique materialized view

---

src/opendata/data7.yaml

The `statiques` dataset query of the opendata service is broken, preventing the container to boot.
As the coordonneesXY field is stored with a generic bytea type, we need to cast it first as a Geometry field before performing actions/queries on it.

🐛(opendata) fix `statiques` dataset SQL query

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/static.py
src/api/qualicharge/schemas/core.py
src/api/tests/api/v1/routers/test_statique.py
src/api/tests/schemas/test_static.py

Now that we've created a materialized view for static data, let's use it in the API!

Integrate Statique Materialized View to the API

---

src/api/cron.json
src/api/qualicharge/cli.py
src/api/tests/schemas/test_static.py
src/api/tests/test_cli.py

We want to be sure that the Statique MV is always up-to-date.

✅(api) test the Statique MV refresh consistency

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Activate and configure Sentry profiling by setting the `SENTRY_PROFILES_SAMPLE_RATE` configuration
- Set request's user (`username`) in Sentry's context
- Add `Localisation.coordonneesXY` unique contraint [BC] 💥
- Implement `Statique` materialized view
- Prefetch user-related groups and operational units in `get_user` dependency
- Improve bulk endpoints permissions checking
- Cache logged user object for `API_GET_USER_CACHE_TTL` seconds to decrease the number of database queries
- CLI: sort groups and operational units alphabetically in the `list-groups` command
- Decrease the number of database queries for dynamic endpoints
- Cache the "get PointDeCharge id from its `id_pdc_itinerance`" database query
- Improve JSON string parsing using pyarrow engine
- Add default values for optional …

🔖(api:minor) bump release to 0.17.0

---

src/dashboard/apps/consent/apps.py
src/dashboard/apps/consent/forms.py
src/dashboard/apps/consent/models.py
src/dashboard/apps/consent/templates/consent/includes/_manage_consents_date_place.html
src/dashboard/apps/consent/templates/consent/manage.html
src/dashboard/apps/consent/tests/test_validators.py
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/validators.py
src/dashboard/apps/consent/views.py

We need to update all consents with the contractual data once they are validated by the user.
The new data to be incorporated are: company information, representative information, control authority information and all information from the form (checkbox, signature date, ...)

✨(dashboard) add validation and data updates for consent management

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Integrate `postgresql_audit` for critical database changes versioning
- Update the list of active operational units
- Upgrade fastapi to `0.115.8`
- Upgrade pydantic to `2.10.6`
- Upgrade pyinstrument to `5.0.1`

🔖(api:minor) bump release to 0.18.0

---

bin/metabase-init
src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/factories/dynamic.py
src/api/tests/api/v1/routers/test_dynamic.py
src/client/qcc/cli/session.py
src/client/qcc/endpoints/dynamic.py
src/client/tests/cli/test_session.py
src/client/tests/endpoints/test_dynamic.py

We need a way to check that session have been properly recorded.
Submit a session UUID if it exists, the API returns a HTTP 200 OK code, else 404.

Add `/dynamique/session/check` endpoint

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py
src/api/qualicharge/api/v1/routers/static.py

Bulk endpoint are not properly documented in the Swagger API docs.

📝(api) improve bulk endpoints documentation

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/dynamic.py

Improve query duration for /dynamique creation endpoint by using background tasks as early as possible.

⚡️(api) use background tasks in /dynamique (bulk) create endpoints

---

.github/workflows/api.yml
src/bench/cli.py

Benchmark of the API using Locust is broken: it generates errors since we are using the Statique MV and the benchmark diff from latest bench database entry is empty.

[API] fix CI bench

---

.github/workflows/dashboard.yml
env.d/dashboard
src/dashboard/CHANGELOG.md
src/dashboard/Pipfile
src/dashboard/Pipfile.lock
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/views.py
src/dashboard/dashboard/settings.py

Users must be notified by email that their consents have been validated.
We use the Brevo service to send transactional emails.

✨(dashboard) add email sending feature using Anymail and Brevo

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/templates/consent/includes/_consent_summary_card.html
src/dashboard/apps/consent/templates/consent/includes/_consent_summary_validated.html
src/dashboard/apps/consent/templates/consent/includes/_no_data_card.html
src/dashboard/apps/consent/templates/consent/validated.html
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/urls.py
src/dashboard/apps/consent/views.py
src/dashboard/apps/core/models.py

Users must be able to view validated consents for the current period

✨(dashboard) add validated consent view

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Implement a new `/dynamique/session/check` endpoint to check if a target session exists or not
- Improve bulk endpoints documentation
- Improve `/dynamique` (bulk) create endpoint performance by using background tasks
- Upgrade cachetools to `5.5.2`
- Upgrade geoalchemy2 to `0.17.1`
- Upgrade psycopg to `3.2.5`
- Upgrade pyarrow to `19.0.1`
- Upgrade pydantic-settings to `2.8.0`
- Upgrade sentry-sdk to `2.22.0`

🔖(api:minor) bump release to 0.19.0

---

src/dashboard/apps/auth/backends.py
src/dashboard/apps/auth/tests/test_backends.py

Currently, ProConnect does not check the format of the SIRET it returns.
We must ensure that this SIRET is in the expected format before saving it in db.

🐛(dashboard) update SIRET handling and add validation in auth backend

---

.github/workflows/dashboard.yml
env.d/dashboard
src/dashboard/apps/auth/models.py
src/dashboard/apps/auth/tests/test_models.py
src/dashboard/dashboard/settings.py

When an admin validates a new user, we need to notify the user by sending a notification.

✨(dashboard) add email notification for user validation

---

src/dashboard/apps/auth/admin.py
src/dashboard/apps/auth/backends.py
src/dashboard/apps/auth/tests/test_backends.py
src/dashboard/apps/home/views.py
src/dashboard/dashboard/settings.py

in admin, we need to be able to easily trigger the retrieval of information of an Entity from the "Annuaire des Entreprises" API. We also need to link this entity to the user who has the SIRET.

✨(dashboard) add user-entity attachment logic on ProConnect user creation

---

.github/workflows/dashboard.yml
env.d/dashboard
src/dashboard/apps/auth/backends.py
src/dashboard/apps/auth/tests/test_backends.py
src/dashboard/dashboard/settings.py

When a new user registers on the dashboard, we must notify the QualiCharge team by sending a notification.

✨(dashboard) add admin notification for new user registration

---

src/dashboard/apps/auth/backends.py
src/dashboard/apps/auth/tests/test_backends.py

The notification sent when a new user registers on the dashboard must contain the user's email.

🩹(dashboard) fix email data key to use user email instead of username

---

src/api/CHANGELOG.md
src/api/qualicharge/models/dynamic.py
src/api/qualicharge/models/static.py
src/api/tests/api/v1/routers/test_dynamic.py
src/api/tests/api/v1/routers/test_statique.py

Some fields seems required in the API payload even if flagged as optional in our models.
Typing optional fields as optional is not sufficient to make them optional, they also need a default value.

🐛(api) add default value to models optional fields

---

.github/workflows/dashboard.yml

Black should be in check mode.

👷(dashboard) enforce Black formatting check in CI pipeline

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/templates/consent/includes/_manage_company_informations.html
src/dashboard/apps/consent/templates/consent/includes/_manage_consents.html
src/dashboard/apps/consent/templates/consent/manage.html
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/views.py

The consent form should only allow the management of a single entity at a time, rather than multiple entities as it currently does.

♻️(dashboard) refactor to manage a single entity instead of multiple in consent form

---

renovate.json

Renovate creates immortal PRs (automatically re-open when closed un-merged). This is a real pain when PR are not relevant, e.g. upgrading Python release too early.
Docs: https://docs.renovatebot.com/key-concepts/pull-requests/#how-to-fix-immortal-prs

🔧(project) avoid Renovate immortal PRs

---

Makefile

We aim to add a `make bootstrap-api` command to streamline and simplify the process of running the API service during development.

🧑‍💻(api) update bootstrap command for API project in makefile

---

Makefile

Include `refresh-api-static` in the Makefile's command list.

🩹(api) add `refresh-api-static` to Makefile commands

---

src/client/CHANGELOG.md
src/client/pyproject.toml

- Add support for new `/manage` API endpoints
- Upgrade anyio to `4.6.1`
- Upgrade httpx to `0.28.0`
- Upgrade Pydantic to `2.9.1`
- Upgrade pydantic-settings to `2.8.1`
- Upgrade typer to `0.15.2`

🔖(client:minor) bump release to 0.3.0

---

src/client/CHANGELOG.md
src/client/qcc/endpoints/manage.py

Corrected docstrings to accurately describe the /manage endpoints and corresponding routes. 
No functional code changes were made.

🩹(client) update docstrings in manage.py to reflect correct endpoints

---

src/api/CHANGELOG.md
src/api/qualicharge/models/static.py
src/api/qualicharge/schemas/core.py
src/api/tests/models/test_static.py
src/api/tests/schemas/test_static.py

When a new PDC has been connected to the CPO's infrastructure, the CPO should be able to declare it to QualiCharge.

🐛(api) allow creating a new PDC the day it has been connected

---

src/api/CHANGELOG.md
src/api/qualicharge/api/v1/routers/manage.py
src/api/tests/api/v1/routers/test_manage.py

When listing stations related to a Amenageur SIREN, we should ignore stations without PDL number as it's still not required yet.

🐛(api) ignore stations without PDL in stations mananagement

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Add manage router and `station/siren` endpoint for the Dashboard
- Allow creating a new PDC the day it has been connected
- Ignore stations without PDL in stations mananagement endpoint

🔖(api:minor) bump release to 0.20.0

---

src/dashboard/apps/consent/managers.py
src/dashboard/apps/consent/models.py
src/dashboard/apps/consent/templates/consent/validated.html
src/dashboard/apps/core/models.py
src/dashboard/apps/core/tests/test_models.py

In the dashboard, we need to display validated consents even if they are a period in the future.
Future periods are defined as those with a start date between today and up to **x** days ahead.

✨(dashboard) add support for upcoming validated consents in dashboard

---

src/dashboard/CHANGELOG.md
src/dashboard/apps/consent/helpers.py
src/dashboard/apps/consent/management/commands/renewconsents.py
src/dashboard/apps/consent/managers.py
src/dashboard/apps/consent/tests/test_commands_renewconsents.py
src/dashboard/apps/consent/tests/test_helpers.py
src/dashboard/apps/core/models.py

We need to perform a daily check to identify consents that are set to expire within _x_ days. 
Any consents approaching their expiration must be duplicated with updated start and end dates.

✨(dashboard) add management command to duplicate expiring consents

---

src/dashboard/apps/consent/helpers.py
src/dashboard/apps/consent/management/commands/renewconsents.py
src/dashboard/apps/consent/tests/test_commands_renewconsents.py
src/dashboard/apps/consent/tests/test_helpers.py

Periodically, we need the ability to generate new consents for delivery points that lack active consent.

✨(dashboard) add command to generate missing consents

---

src/dashboard/apps/consent/static/apps/consent/css/app.css
src/dashboard/apps/consent/static/apps/consent/js/app.js
src/dashboard/apps/consent/templates/consent/includes/_manage_company_informations.html
src/dashboard/apps/consent/templates/consent/includes/_manage_consents.html
src/dashboard/apps/consent/templates/consent/manage.html

In the consent form, the list of PDLs can be long.
To improve the user experience, we want to limit the page length and therefore make this list scrollable.

🚸(dashboard) Enhance consent management UI and add PDL validation logic

---

src/api/logging-config.prod.yaml
src/api/start.sh

API instances running on Scalingo already have activated router logs, hence uvicorn access logs seems useless duplicates.

🔇(api) remove access logs in production

---

src/dashboard/apps/consent/tests/test_helpers.py
src/dashboard/apps/consent/tests/test_utils.py
src/dashboard/apps/consent/utils.py

Previously, the start date was timezone-naive, which could cause inconsistencies in environments expecting timezone-aware datetimes.

🩹(dashboard) set UTC timezone for consent_start_date function

---

src/dashboard/CHANGELOG.md
src/dashboard/cron.json
src/dashboard/readme.md

We need to schedule the execution of `syncdeliverypoints`, `renewconsents`, and `notifawaitingconsents` commands.

✨(dashboard) add cron job configuration to schedule management tasks

---

docs/schemas.md

API users don't understand field constraints.

📝(api) add documentation on data model constraints

---

Makefile

Recent changes in prefect deployment strategy broke local development workflow: deployments are not created locally

🔨(prefect) create all deployments once prefect is up

---

src/api/CHANGELOG.md
src/api/qualicharge/models/static.py
src/api/qualicharge/schemas/core.py
src/api/qualicharge/schemas/utils.py
src/api/tests/schemas/test_static.py
src/api/tests/schemas/test_utils.py

When a user tries to update a Localisation that as many entries with the same address but an already referenced set of coordinates (which is perfectly acceptable), the API returns an error (for statique creation or update).
Since the `coordonneesXY` field is the only unique field for the `Localisation` model, it should be used to discriminate existing objects from those that need to be created.

🐛(api) update localisation using the coordonneesXY field

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Update the list of active operational units
- Upgrade alembic to `1.15.2`
- Upgrade fastapi to `0.115.12`
- Upgrade psycopg to `3.2.6`
- Upgrade pydantic to `2.11.1`
- Upgrade pydantic-extra-types to `2.10.3`
- Upgrade sentry-sdk to `2.25.0`
- Upgrade setuptools to `78.1.0`
- Update `Localisation` discriminating field to `coordonneesXY` for statique-related helpers

🔖(api:minor) bump release to 0.21.0

---

src/dashboard/apps/consent/templates/consent/includes/_consent_summary_validated_card_content.html
src/dashboard/apps/consent/templates/consent/includes/_manage_consents.html
src/dashboard/apps/consent/templates/consent/validated.html
src/dashboard/apps/consent/templatetags/__init__.py
src/dashboard/apps/consent/templatetags/consent_filters.py
src/dashboard/apps/consent/tests/test_templatetags.py
src/dashboard/apps/consent/tests/test_views.py
src/dashboard/apps/consent/views.py
src/dashboard/apps/core/factories.py
src/dashboard/apps/core/models.py
src/dashboard/apps/core/tests/test_models.py

- The consent display must not include duplicate `delivery points`.  
- Each `delivery point` row must display the associated `stations` along with a list of `id_station_itinerance` for each `station`.

🚸(dashboard) add grouped station in templates

---

src/api/CHANGELOG.md
src/api/qualicharge/migrations/versions/2d5ecaec5672_fix_status_hypertable_creation.py
src/api/qualicharge/schemas/core.py

As we defined Status.id as the table primary key (with unique constraint), TimescaleDB refused to create our hypertable. This is a well-known, [documented issue](https://docs.timescale.com/use-timescale/latest/hypertables/hypertables-and-unique-indexes/#create-a-hypertable-from-a-table-with-unique-indexes).
We need instead to add a composite unique constraint using both the `id` and `horodatage` fields.

🐛(api) Switch the Status table to a TimescaleDB hypertable

---

src/prefect/indicators/historicize/up.py
src/prefect/indicators/utils.py
src/prefect/tests/historicize/test_up.py
src/prefect/tests/infrastructure/test_i1.py

Historicization (`calculate` function, module `up`) is ineffective when `start` parameter is None .

🐛(prefect) allow historicization with None start

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Clean database static orphan entries using a SQL script ran as a cronjob task
- Add time and fk-related missing database indexes for status & session tables
- Docs: update data schema restrictions
- Docs: add usage section
- Switch `Status` table to a TimescaleDB hypertable

🔖(api:minor) bump release to 0.22.0

---

.github/workflows/api.yml
.github/workflows/prefect.yml
docker-compose.yml
src/api/CHANGELOG.md
src/api/qualicharge/migrations/versions/2d5ecaec5672_fix_status_hypertable_creation.py
src/api/qualicharge/migrations/versions/d7425ed47afd_fix_session_hypertable_creation.py
src/api/qualicharge/schemas/core.py

As we defined Session.id as the table primary key (with unique constraint), TimescaleDB refused to create our hypertable.
We need instead to add a composite unique constraint using both the ID and start fields. Since `Session` table changes are tracked using database triggers, we need to upgrade TimescaleDB to at least `2.18.0`.
---
We need to wait for our cloud provider to upgrade TimescaleDB from the `2.17.2` to at least `2.18.0`.
---
*Update*: we've upgraded TimescaleDB both in staging and production to `2.19`.

🐛(api) switch the Session table to a TimescaleDB hypertable

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Switch `Session` table to a TimescaleDB hypertable

🔖(api:patch) bump release to 0.22.1

---

src/prefect/prefect.yaml

Deployment of indicators u5, u6, u9 and u10 failed because parameters are missing

🐛(prefect) add missing parameters for deployments

---

src/dashboard/apps/core/models.py
src/dashboard/apps/core/tests/test_models.py
src/dashboard/apps/home/views.py
src/dashboard/apps/renewable/templates/renewable/includes/_summary_pending_card_content.html
src/dashboard/apps/renewable/templates/renewable/includes/_summary_submitted_card_content.html
src/dashboard/apps/renewable/views.py

The renewable logic should be added to the views and templates

✨(dashboard) enhance renewable logic in views and templates

---

src/prefect/indicators/historicize/up.py
src/prefect/indicators/utils.py

Historicization fails when Standard deviation is `nan`.
Standard deviation is `nan` when Variance is negative (reason : data variations are small and precision errors appear).

🐛(prefect) correct variance historicization error

---

src/dashboard/apps/core/templatetags/__init__.py
src/dashboard/apps/core/templatetags/dashboard_filters.py
src/dashboard/apps/core/tests/test_dashboard_filters.py
src/dashboard/apps/renewable/templates/renewable/includes/_manage_meters.html

We need a templatetag to sor delivery points by station.

🚸(renewable) add `sort_by_station` filter and integrate it into template

---

src/prefect/clean-offline-workers.sh

The `clean-offline-workers.sh` cronjob does nothing. Old offline workers are never deleted.
Worker id and the UUID in its name are different, we should use its full name in the API.

🐛(prefect) fix offline workers cleanup script

---

.github/workflows/dashboard.yml
env.d/dashboard
src/dashboard/apps/core/models.py
src/dashboard/apps/core/templatetags/dashboard_filters.py
src/dashboard/apps/core/tests/test_models.py
src/dashboard/apps/core/tests/test_utils.py
src/dashboard/apps/core/utils.py
src/dashboard/apps/renewable/forms.py
src/dashboard/apps/renewable/tests/test_forms.py
src/dashboard/apps/renewable/tests/test_view.py
src/dashboard/dashboard/settings.py

Add validation rule for user-submitted meter readings: entries must fall within a specific timeframe relative to the previous quarter.
Readings must be between [X] days before the previous quarter's end date and the previous quarter's end date.

✨(renewable) update logic to handle previous quarter data

---

src/dashboard/apps/core/tests/test_utils.py
src/dashboard/apps/core/utils.py
src/dashboard/apps/renewable/templates/renewable/includes/_manage_meters.html
src/dashboard/apps/renewable/templatetags/__init__.py
src/dashboard/apps/renewable/templatetags/renewable_tags.py
src/dashboard/apps/renewable/tests/test_renewable_tags.py

we need to display the quarterly period information in the energy statement management form to help users track and validate statements based on the corresponding quarter.

🚸(renewable) add template tag for quarter period display

---

src/dashboard/apps/renewable/templates/renewable/includes/_manage_meters.html
src/dashboard/apps/renewable/templates/renewable/includes/_summary_submitted_card_content.html
src/dashboard/apps/renewable/templates/renewable/submitted.html
src/dashboard/apps/renewable/tests/test_view.py
src/dashboard/apps/renewable/urls.py
src/dashboard/apps/renewable/views.py

We need a page that displays all submitted energy meter readings. 
The listing should be ordered by:
- Submission date (most recent first)
- Station names (alphabetically)

🚸(dashboard) add submitted renewables view with sorting

---

src/api/CHANGELOG.md
src/api/qualicharge/models/static.py
src/api/tests/models/test_static.py

While publishing our static open dataset, we noticed poor quality data in `restriction_gabarit` field and potential issues with unstripped strings.

Improve `Statique` model string fields quality

---

src/dashboard/apps/renewable/templates/renewable/includes/_manage_delivery_points.html
src/dashboard/apps/renewable/templates/renewable/includes/_manage_meters.html

In the energy meter submission form, add a default value, if there are no previous meter readings
Repositions hidden input fields for consistency across templates.

🚸(dashboard) add fallback for meter readings and refactor hidden inputs

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Clean activity table every day using a cronjob
- Update `id_station_itinerance` field examples in the swagger documentation
- `Statique` model string fields are now stripped
- `Statique.restriction_gabarit` field should be at least 2 characters long
- Update the list of active operational units (twice)
- Upgrade `alembic` to `1.16.1`
- Upgrade `cachetools` to `6.0.0`
- Upgrade `geopandas` to `1.1.0`
- Upgrade `pandas` to `2.3.0`
- Upgrade `psycopg` to `3.2.9`
- Upgrade `pydantic` to `2.11.5`
- Upgrade `pyinstrument` to `5.0.2`
- Upgrade `sentry-sdk` to `2.29.0`
- Upgrade `setuptools` to `80.9.0`
- Upgrade `typer` to `0.16.0`

🔖(api:minor) bump release to 0.24.0

---

src/dashboard/apps/core/models.py
src/dashboard/apps/core/tests/test_models.py
src/dashboard/apps/renewable/templates/renewable/includes/_summary_delivery_points.html
src/dashboard/apps/renewable/templates/renewable/includes/_summary_delivery_points_content.html
src/dashboard/apps/renewable/tests/test_view.py
src/dashboard/apps/renewable/views.py

Currently, users cannot access the delivery points management interface unless at least one delivery point has the "has_renewable" checked.

🐛(dashboard) fix access to the delivery points management in renewable app

---

src/dashboard/dashboard/urls.py
src/dashboard/templates/base.html
src/dashboard/templates/robots.txt

- add an 'opengraph' block with a 'noindex' meta tag to prevent search engines from indexing certain pages.
- add robots.txt

📈(dashboard) add 'noindex' meta tag block to base template

---

src/dashboard/cron.json

Add a new cron job to trigger the `notifopening` command for renewable opening notifications on specified dates.

✨(dashboard) add cron schedule for renewable opening notifications

---

src/dashboard/CHANGELOG.md
src/dashboard/Pipfile.lock

Upgraded `pydantic` to 2.10.0 and `pygments` to 2.19.2. 
Re-added `types-python-dateutil` dependency. 
Updated hash values to reflect changes.

⬆️(dashboard) update Pipfile.lock dependencies

---

src/api/scripts/data_retention_procedure.sql

Concatenating strings in a PostgreSQLprocedure call argument is not allowed.
The easiest way to fix this is to set the `DYNAMIC_CLEAN_AFTER` environment variable to expected JSON argument, e.g. `'{"drop_after":"20 days"}'`

🐛(api) fix timescaledb cleanup parameter

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py

- Add a configurable retention policy for `Status` and `Session` data
- Create new database indexes:
- `ix_pointdecharge_station_id`
- `ix_station_amenageur_id`
- `ix_station_operateur_id`
- Update the list of active operational units
- Upgrade `alembic` to `1.16.2`
- Upgrade `cachetools` to `6.1.0`
- Upgrade `FastAPI` to `0.115.13`
- Upgrade `Pydantic` to `2.11.7`
- Upgrade `pydantic-settings` to `2.10.0`
- Upgrade `sentry-sdk` to `2.30.0`
- Upgrade `urllib3` to `2.5.0`
- Drop database indexes:
- `status_horodatage_idx`
- `ix_status_horodatage_pdc_id`
- `session_start_idx`
- `ix_session_start_pdc_id`

🔖(api:minor) bump release to 0.25.0

---

src/opendata/CHANGELOG.md
src/opendata/data7.yaml

Current database query is too greedy and the corresponding HTTP request always fails when it reaches the request timeout.
For now, we only expose recent statuses, not all charge points will have a status. We will fill the blanks (if required) in a near future.

⚡️(opendata) use LatestStatus table

---

src/prefect/CHANGELOG.md
src/prefect/indicators/schemas.py

Now that daily indicators jobs run for a while, we need to tune our table indexes.
We've updated the base indicator model to reflect changes operated in the staging and production tables:
```sql
-- Staging table
CREATE INDEX ix_staging_code ON staging (code);
CREATE INDEX ix_staging_level ON staging (level);
CREATE INDEX ix_staging_period ON staging (period);
CREATE INDEX ix_staging_timestamp ON staging (timestamp);
-- Production table
CREATE INDEX ix_production_code ON production (code);
CREATE INDEX ix_production_level ON production (level);
CREATE INDEX ix_production_period ON production (period);
CREATE INDEX ix_production_timestamp ON production (timestamp);
```

🗃️(prefect) update indicators table indexes

---

src/api/CHANGELOG.md
src/api/pyproject.toml
src/api/qualicharge/__init__.py
src/api/uv.lock

- Implement `PointDeCharge` and `Station` soft-delete [BC]
- Add new API endpoints for charge point (and station) decommissioning
- Update the list of active operational units
- Upgrade `pandas` to `2.3.2`
- Upgrade `pyinstrument` to `5.1.1`
- Upgrade `sentry-sdk` to `2.35.0`
- Upgrade `typer` to `0.16.1`

🔖(api:minor) bump release to 0.29.0
